import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateChallanPDF = (challan: any) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(234, 179, 8); // Tailwind Yellow 500 equivalent
  doc.text('MINI ERP', 14, 22);
  
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text('Sales Challan / Invoice', 14, 30);
  
  // Details
  doc.setFontSize(10);
  doc.text(`Challan No: ${challan.challanNumber}`, 14, 45);
  doc.text(`Date: ${new Date(challan.createdAt).toLocaleDateString()}`, 14, 50);
  doc.text(`Status: ${challan.status}`, 14, 55);

  // Customer Info
  doc.setFontSize(11);
  doc.text('Bill To:', 120, 45);
  doc.setFontSize(10);
  doc.text(`${challan.customer.name}`, 120, 50);
  doc.text(`${challan.customer.businessName}`, 120, 55);
  if (challan.customer.gstNumber) {
    doc.text(`GST: ${challan.customer.gstNumber}`, 120, 60);
  }

  // Items Table
  const tableColumn = ["#", "Product", "SKU", "Qty", "Unit Price", "Total"];
  const tableRows: any[] = [];
  
  let grandTotal = 0;

  challan.items.forEach((item: any, index: number) => {
    const total = parseFloat(item.unitPrice) * item.quantity;
    grandTotal += total;
    const itemData = [
      index + 1,
      item.productName,
      item.sku,
      item.quantity,
      `$${parseFloat(item.unitPrice).toFixed(2)}`,
      `$${total.toFixed(2)}`
    ];
    tableRows.push(itemData);
  });

  autoTable(doc, {
    startY: 70,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [234, 179, 8], textColor: 255 },
    styles: { fontSize: 9 },
  });

  // Footer Total
  const finalY = (doc as any).lastAutoTable.finalY || 70;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Grand Total: $${grandTotal.toFixed(2)}`, 14, finalY + 15);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by ${challan.createdBy.name} via Mini ERP system.`, 14, finalY + 30);

  doc.save(`${challan.challanNumber}.pdf`);
};
